/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class chnagepass extends javax.swing.JFrame {
        Connection con=null;
        
        Statement st=null;
        
    /**
     * Creates new form chnagepass
     */
    public chnagepass() {
        initComponents();
        //JOptionPane.showMessageDialog(null, "Hii");
         try {
            con=DbUtill.getConnection();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oldpass = new javax.swing.JPasswordField();
        newpass = new javax.swing.JPasswordField();
        newcnfrm = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        shpass = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 390));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        oldpass.setToolTipText("Enter Old Password");
        getContentPane().add(oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 75, 180, 25));

        newpass.setToolTipText("Enter New Password");
        getContentPane().add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 145, 180, 25));

        newcnfrm.setToolTipText("Confirm Your Password");
        getContentPane().add(newcnfrm, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 210, 180, 25));
        newcnfrm.getAccessibleContext().setAccessibleName("");

        jButton1.setBackground(new java.awt.Color(7, 171, 202));
        jButton1.setText("CHANGE");
        jButton1.setToolTipText("Set Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, 30));

        shpass.setText("Show Password");
        shpass.setToolTipText("Show Password");
        shpass.setContentAreaFilled(false);
        shpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shpassActionPerformed(evt);
            }
        });
        getContentPane().add(shpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 250, -1, -1));

        jButton2.setBackground(new java.awt.Color(7, 171, 202));
        jButton2.setText("CLOSE");
        jButton2.setToolTipText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ChndPw1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -10, 720, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String old=String.valueOf(oldpass.getPassword());
        String newp=String.valueOf(newpass.getPassword());
        String newc=String.valueOf(newcnfrm.getPassword());
        String stt="SELECT * FROM `users` WHERE `password`='"+old+"';";
        boolean success=false;
        if(newp.compareTo(newc)==0){
            try {
            st=con.createStatement();
            ResultSet r=st.executeQuery(stt);
            if(r.next()){
                  success=true;
            }
            st.close();
         
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
            if(success){
               try{
                String stt1="UPDATE `users` SET `password` = '"+newp+"' WHERE `users`.`password` = '"+old+"' ";
                st=con.createStatement();
                st.executeUpdate(stt1);
                JOptionPane.showMessageDialog(null,"Done");  
               } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
               
                
            }else{
                JOptionPane.showMessageDialog(null, "Old password does not match", "Error",JOptionPane.WARNING_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "New Password does not match", "Error",JOptionPane.WARNING_MESSAGE);
        }
        oldpass.setText(null);
        newpass.setText(null);
        newcnfrm.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void shpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shpassActionPerformed
         if(shpass.isSelected()){
           
            oldpass.setEchoChar((char)0);
            newpass.setEchoChar((char)0);
            newcnfrm.setEchoChar((char)0);
        }else{
           
            oldpass.setEchoChar('*');
            newpass.setEchoChar('*');
            newcnfrm.setEchoChar('*');

        }
    }//GEN-LAST:event_shpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chnagepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chnagepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chnagepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chnagepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chnagepass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField newcnfrm;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JPasswordField oldpass;
    private javax.swing.JCheckBox shpass;
    // End of variables declaration//GEN-END:variables
}
