/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {
         Connection conn=null;
        PreparedStatement st=null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocation(300, 100);
        initialize();
         try {
                conn=DbUtill.getConnection();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
         setHospitals();
    }
    private void initialize(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ico.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        username = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(676, 556));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(169, 221, 231));
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 221, 231)));
        jComboBox1.setOpaque(false);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 270, 40));

        password.setBackground(new java.awt.Color(169, 221, 231));
        password.setBorder(null);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 270, 30));

        jButton1.setBackground(new java.awt.Color(103, 196, 212));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginButton.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 110, 110));

        jButton2.setBackground(new java.awt.Color(103, 196, 212));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Loginquit.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 69, 50));

        jRadioButton1.setBackground(new java.awt.Color(38, 172, 192));
        jRadioButton1.setText("Show Password");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, -1));

        username.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Administrator", "ICU Operator", "Director" }));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 270, 30));

        jLabel5.setBackground(new java.awt.Color(210, 222, 238));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGINBack.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       if(jRadioButton1.isSelected()){
           
            password.setEchoChar((char)0);
        }else{
            password.setEchoChar('*');

        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usr=username.getSelectedItem().toString();
        if(usr.equalsIgnoreCase("Select")){
            JOptionPane.showMessageDialog(null, "Select your Usertype", "Error",JOptionPane.WARNING_MESSAGE);
        }else{
        try {
            
            String psw=String.valueOf(password.getPassword());
            st=conn.prepareStatement("SELECT * FROM `users` WHERE `user`=?AND`password`=?");
            st.setString(1, usr);
            st.setString(2, psw);
            ResultSet rs= st.executeQuery();
            String hos=jComboBox1.getSelectedItem().toString();
           // String[] args = null;
//            Statement s=conn.createStatement();
//            ResultSet rs1= s.executeQuery("Select * from user where hospitalname="+hos+"; ");
            
            
            if(rs.next()){
                String user=rs.getString("user");
                if("Administrator".equalsIgnoreCase(user)){
                    //System.out.println(rs.getString("user"));
                   AdminGUI ad=new AdminGUI();
                   ad.setVisible(true);
                   conn.close();
                    dispose();
                }else
                if(!(hos.equalsIgnoreCase("Select"))){
                    if("Director".equalsIgnoreCase(user))
                    {
                    DirectorGUI dr=new DirectorGUI(hos);
                    dr.setVisible(true);
                    conn.close();
                    dispose();
                    }
                    if("ICU Operator".equalsIgnoreCase(user))
                    {
                    UserGUI us=new UserGUI(hos);
                    us.setVisible(true);
                    conn.close();
                    dispose();
                    }
                    }else
                    {
                        JOptionPane.showMessageDialog(null, "Select your Hospital", "Error",JOptionPane.WARNING_MESSAGE);
                
                    }
                    
                    
                }
                else if(usr.isEmpty()||psw.isEmpty()){
                    
                    if(psw.isEmpty())
                        {
                        JOptionPane.showMessageDialog(null, "Please Enter Password", "Error",JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    else if(!(psw.isEmpty())){
                        JOptionPane.showMessageDialog(null, "Incorrect Username or Password", "Error",JOptionPane.WARNING_MESSAGE);
                        clear();
                    }
                
                
                
                    
                 
            

        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
        
        }  
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void clear(){
        username.setSelectedIndex(0);
        password.setText("");
        jComboBox1.setSelectedIndex(0);
    }
     public void setHospitals(){
        String sq="select HospitalName from hospitals";
        Statement s=null;
        String []n = null;
        int i=0;
            try {
                s=conn.createStatement();
                ResultSet rs2=s.executeQuery(sq);
               
                while(rs2.next()){
                   //System.out.println(rs.getNString("hospitalname"));
                 
                  jComboBox1.addItem(rs2.getNString("hospitalname"));

                }
                
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, ex);
            }
        
        
        
    }
    /**
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> username;
    // End of variables declaration//GEN-END:variables
}
